<?php

return [
    'tax_rates' => [
        1 => 'Texas State Sales Tax',
        2 => 'Florida Sales Tax',
        3 => 'Exempt',
        4 => 'Not Applicable',
    ],
    'equipment_status' => [
        1 => 'new',
        2 => 'ready',
        3 => 'dirty',
        4 => 'broken',
        5 => 'lost',
        6 => 'decommissioned',
        7 => 'assigned',
    ],
    'training_categories' => [
        1 => 'Core',
        2 => 'HazCom',
        3 => 'Leadership',
        4 => 'Science',
        5 => 'Service',
    ],
    'training_tests' => [
        1 => 'Bloodborne Pathogens',
        2 => 'HIPAA',
        3 => 'Sexual Harassment',
        4 => 'Chemical Labels',
        5 => 'Eye Wash',
        6 => 'Hazard Communications',
        7 => 'Safety Data Sheets',
        8 => 'Accountability',
        9 => 'Attitude Part 1',
        10 => 'Attitude Part 2',
        11 => 'Dealing With Difficult People 1',
        12 => 'Dealing With Difficult People 2',
        13 => 'Dealing With Difficult People 3',
        14 => 'Decision Making Part 1',
        15 => 'Decision Making Part 2',
        16 => 'Leadership - Complacency',
        17 => 'Leadership vs Management',
        18 => 'Servant Leadership',
        19 => 'Microbiology I',
        20 => 'Microbiology II',
        21 => 'ATP Sampling',
        22 => 'Education Environment',
        23 => 'Education Environment: Athletics - Locker Rooms',
        24 => 'GermBlast Inventory Management',
        25 => 'GermBlast Pretreatment',
        26 => 'GermBlast Shield Process',
        27 => 'GermBlast Spray',
        28 => 'GermBlast Steam',
        29 => 'Healthcare',
        30 => 'Personal Protective Equipment/Uniform',
    ],
];
