<?php

return [

    'Company' => [
        'company.view',
        'company.my.view',
        'company.create',
        'company.update',
        'company.delete',
        'company.location.manage',
        'company.people.manage',
        'company.tag.manage',
        'company.file.manage',
        'company.task.manage',
        'company.activity.manage',
        'company.dashboard.view',
        'company.iaq.manage',
        'company.biological.manage',
        'company.survey.manage',
        'company.water.manage',
    ],

    'People' => [
        'people.view',
        'people.create',
        'people.update',
        'people.delete',
        'people.my.view',
        'people.animal_care.view',
        'people.marketing_contacts.view',
        'people.sequence_healthcare.view',
        'people.task.manage',
        'people.activity.manage',
        'people.company.manage',
        'people.tag.manage',
        'people.file.manage',
        'people.field.manage',
    ],

    'Lead' => [
        'lead.view',
        'lead.create',
        'lead.update',
        'lead.delete',
        'lead.my.view',
        'lead.hot.view',
        'lead.added_this_week.view',
        'lead.closing_this_week.view',
        'lead.open.view',
        'lead.watching.view',
        'lead.task.manage',
        'lead.activity.manage',
        'lead.tag.manage',
        'lead.file.manage',
        'lead.field.manage',
        'lead.product.manage',
        'lead.forecasting.manage',
        'lead.ajax.update',
        'lead.stage.initial.schedule',
        'lead.stage.initial.complete',
        'lead.stage.initial.reopen',
        'lead.stage.initial.reset',
        'lead.stage.site_survey.schedule',
        'lead.stage.site_survey.complete',
        'lead.stage.site_survey.reopen',
        'lead.stage.site_survey.reset',
    ],

    'Survey Proposal' => [
        'survey.proposal.view',
        'survey.proposal.create',
        'survey.proposal.facility.view',
        'survey.proposal.facility.create',
        'survey.proposal.facility.update',
        'survey.proposal.equipment.view',
        'survey.proposal.equipment.create',
        'survey.proposal.equipment.update',
        'survey.proposal.pricing.view',
        'survey.proposal.view.details',
        'survey.proposal.download',
        'pricing.proposal.create',
        'pricing.proposal.update',
        'pricing.proposal.delete',
    ],

];
