<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class JobProfitabilityController extends Controller
{
    public function index()
    {
        $records = [
            [
                'client' => 'Faith Church Lubbock',
                'date' => '06/01/26',
                'price' => '419.58',
                'hours' => '6.29',
                'ot' => '-',
                'budget_hours' => '4.86',
                'ratio_hours' => '1.29',
                'actual_labor' => '117.10',
                'budget_labor' => '117.36',
                'ratio_labor' => '1.00',
                'delta' => '-0.26',
                'row_class' => '',
                'text_color' => '',
                'price_color' => '',
                'delta_color' => ''
            ],
            [
                'client' => 'Grace Surgical Hospital',
                'date' => '06/06/26',
                'price' => '1,932.00',
                'hours' => '11.04',
                'ot' => '-',
                'budget_hours' => '22.40',
                'ratio_hours' => '0.49',
                'actual_labor' => '205.34',
                'budget_labor' => '540.96',
                'ratio_labor' => '0.38',
                'delta' => '-335.62',
                'row_class' => 'row-green',
                'text_color' => 'text-success',
                'price_color' => 'text-success',
                'delta_color' => 'text-success'
            ],
            [
                'client' => 'Hobbs Municipal Schools',
                'date' => '06/05/26',
                'price' => '36,453.53',
                'hours' => '326.36',
                'ot' => '23.27',
                'budget_hours' => '422.60',
                'ratio_hours' => '0.83',
                'actual_labor' => '7,130.87',
                'budget_labor' => '10,205.80',
                'ratio_labor' => '0.70',
                'delta' => '-3,074.93',
                'row_class' => 'row-green',
                'text_color' => 'text-success',
                'price_color' => 'text-success',
                'delta_color' => 'text-success'
            ],
            [
                'client' => 'Hobbs Municipal Schools',
                'date' => '06/08/26',
                'price' => '1,200.00',
                'hours' => '-',
                'ot' => '-',
                'budget_hours' => '-',
                'ratio_hours' => '-',
                'actual_labor' => '-',
                'budget_labor' => '-',
                'ratio_labor' => '-',
                'delta' => '-',
                'row_class' => 'row-yellow',
                'text_color' => '',
                'price_color' => '',
                'delta_color' => ''
            ],
            [
                'client' => 'McLane High Plains',
                'date' => '06/06/26',
                'price' => '1,045.91',
                'hours' => '6.68',
                'ot' => '-',
                'budget_hours' => '12.12',
                'ratio_hours' => '0.55',
                'actual_labor' => '124.25',
                'budget_labor' => '292.68',
                'ratio_labor' => '0.42',
                'delta' => '-168.43',
                'row_class' => 'row-green',
                'text_color' => 'text-success',
                'price_color' => 'text-success',
                'delta_color' => 'text-success'
            ],
            [
                'client' => 'Milestones Development & Play Park',
                'date' => '06/07/26',
                'price' => '609.31',
                'hours' => '5.62',
                'ot' => '-',
                'budget_hours' => '7.06',
                'ratio_hours' => '0.80',
                'actual_labor' => '101.16',
                'budget_labor' => '170.50',
                'ratio_labor' => '0.59',
                'delta' => '-69.34',
                'row_class' => 'row-green',
                'text_color' => 'text-success',
                'price_color' => 'text-success',
                'delta_color' => 'text-success'
            ],
            [
                'client' => 'Northwest Texas Healthcare System',
                'date' => '06/11/26',
                'price' => '6,696.01',
                'hours' => '360.72',
                'ot' => '14.83',
                'budget_hours' => '77.64',
                'ratio_hours' => '4.88',
                'actual_labor' => '6,413.51',
                'budget_labor' => '1,875.00',
                'ratio_labor' => '3.42',
                'delta' => '4,538.51',
                'row_class' => 'row-pink',
                'text_color' => 'text-danger',
                'price_color' => 'text-danger',
                'delta_color' => 'text-danger'
            ],
            [
                'client' => 'NWTHS - Cardiovascular Center',
                'date' => '06/07/26',
                'price' => '1,700.00',
                'hours' => '11.09',
                'ot' => '-',
                'budget_hours' => '19.72',
                'ratio_hours' => '0.56',
                'actual_labor' => '173.00',
                'budget_labor' => '476.24',
                'ratio_labor' => '0.36',
                'delta' => '-303.24',
                'row_class' => 'row-green',
                'text_color' => 'text-success',
                'price_color' => 'text-success',
                'delta_color' => 'text-success'
            ],
            [
                'client' => 'NWTHS - Georgia Balance Center',
                'date' => '06/07/26',
                'price' => '1,623.32',
                'hours' => '15.67',
                'ot' => '-',
                'budget_hours' => '18.81',
                'ratio_hours' => '0.83',
                'actual_labor' => '255.76',
                'budget_labor' => '454.26',
                'ratio_labor' => '0.56',
                'delta' => '-198.50',
                'row_class' => 'row-green',
                'text_color' => 'text-success',
                'price_color' => 'text-success',
                'delta_color' => 'text-success'
            ],
            [
                'client' => 'NWTHS - JO Wyatt Clinic',
                'date' => '06/05/26',
                'price' => '5,043.32',
                'hours' => '193.95',
                'ot' => '226.33',
                'budget_hours' => '58.45',
                'ratio_hours' => '7.19',
                'actual_labor' => '8,837.66',
                'budget_labor' => '1,411.55',
                'ratio_labor' => '6.26',
                'delta' => '7,426.11',
                'row_class' => 'row-pink',
                'text_color' => 'text-danger',
                'price_color' => 'text-danger',
                'delta_color' => 'text-danger'
            ],
            [
                'client' => 'NWTHS - Sports & Ortho',
                'date' => '06/07/26',
                'price' => '1,053.30',
                'hours' => '20.51',
                'ot' => '-',
                'budget_hours' => '12.21',
                'ratio_hours' => '1.68',
                'actual_labor' => '319.96',
                'budget_labor' => '294.87',
                'ratio_labor' => '1.09',
                'delta' => '25.09',
                'row_class' => '',
                'text_color' => '',
                'price_color' => '',
                'delta_color' => ''
            ],
            [
                'client' => 'NWTHS - Wound Care & Hyperbaric Oxygen Therapy',
                'date' => '06/05/26',
                'price' => '1,243.30',
                'hours' => '26.01',
                'ot' => '-',
                'budget_hours' => '14.42',
                'ratio_hours' => '1.80',
                'actual_labor' => '405.76',
                'budget_labor' => '348.24',
                'ratio_labor' => '1.17',
                'delta' => '57.52',
                'row_class' => '',
                'text_color' => '',
                'price_color' => '',
                'delta_color' => ''
            ]
        ];

        return view('admin.reports.profitability', compact('records'));
    }
}
